name: Build and Release WinForms App

on:
  push:
    tags:
      - "v*"   # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Change this to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish Portable EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./portable

      - name: Upload Portable EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: winforms-portable
          path: ./portable/MyApp.exe

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Portable EXE
        uses: actions/download-artifact@v4
        with:
          name: winforms-portable
          path: ./portable/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./portable/MyApp.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "🚀 New release of MyApp!"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
