name: Build and Release WinForms App

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: windows-latest  # Use Windows for building WinForms apps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"  # Change this to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish as Single EXE
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
          # Show the contents of the directory where the app is published
          dir bin\Release\net8.0\win-x64\publish\
        shell: powershell

      - name: Install WinRAR
        run: choco install winrar -y
        shell: powershell

      - name: Package Compiled Files as RAR
        run: |
          # Verify the publish folder exists and show its contents
          if (Test-Path "bin\Release\net8.0\win-x64\publish") {
            Write-Host "Publish folder exists"
            dir bin\Release\net8.0\win-x64\publish\  # Display folder contents for debugging
          } else {
            Write-Host "Publish folder does not exist"
            exit 1
          }

          # Create the RAR file with the compiled EXE and dependencies
          & "C:\Program Files\WinRAR\WinRAR.exe" a -r CompiledFiles.rar bin\Release\net8.0\win-x64\publish\*

          # Check if the RAR file was created
          if (Test-Path "CompiledFiles.rar") {
            Write-Host "CompiledFiles.rar created"
          } else {
            Write-Host "CompiledFiles.rar not created"
            exit 1
          }

          # Move the .rar file to the GitHub workspace for release
          mv .\CompiledFiles.rar ${{ github.workspace }}
        shell: powershell

      - name: Package Source Code as RAR
        run: |
          # RAR the source code (excluding unnecessary files)
          & "C:\Program Files\WinRAR\WinRAR.exe" a -r SourceCode.rar *
          # Move the .rar file to the workspace for release
          mv .\SourceCode.rar ${{ github.workspace }}
        shell: powershell

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CompiledFiles.rar
            SourceCode.rar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use your Personal Access Token (PAT)
